import fs from 'node:fs/promises';
import path from 'node:path';

import { FRONTEND_MANIFEST_PATH, PROJECT_ROOT, SYNC_STATE_PATH } from './config.mjs';
import { discoverMedia } from './discover.mjs';
import {
  credentialStatus, describeUploadError, fetchRemoteAssets, isConfigured, loadEnvironment,
  planFor, uploadAsset,
} from './cloudinary.mjs';

/**
 * Media synchronisation for BANG PRIVATE TATTOOS.
 *
 *   npm run media:check              local inventory and drift, no network writes
 *   npm run media:sync -- --dry-run  what would upload, no Cloudinary mutation
 *   npm run media:sync               performs the uploads
 *
 * Administrative tooling. It never runs in the browser, never runs as part of
 * `npm run build`, and never deletes anything from Cloudinary.
 */

const MODE = process.argv[2] === 'check' ? 'check' : 'sync';
const DRY_RUN = process.argv.includes('--dry-run');
const CATEGORY_FILTER = (() => {
  const flag = process.argv.find(argument => argument.startsWith('--only='));
  return flag ? flag.slice('--only='.length) : null;
})();

const CATEGORY_ORDER = ['videos', 'carousel', 'artists', 'galleries', 'branding'];

const pad = (value, width) => String(value).padStart(width);

async function readJson(file, fallback) {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8'));
  } catch {
    return fallback;
  }
}

async function writeJson(file, data) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

/**
 * The manifest the application reads.
 *
 * Public metadata only: identifiers, dimensions, format, size. No key, no
 * secret, no signature — nothing here would be unsafe in a public bundle.
 */
function buildFrontendManifest({ assets, state, cloudName }) {
  const entries = assets
    .filter(asset => state[asset.relativePath]?.publicId)
    .map(asset => {
      const record = state[asset.relativePath];
      return {
        // A portrait's stable key is the artist, not the photograph's
        // filename: swapping the photo later must not change the id the
        // application looks it up by.
        id: asset.category === 'artists' && asset.artistId
          ? asset.artistId
          : asset.contentId ?? asset.fileName,
        publicId: record.publicId,
        resourceType: record.resourceType,
        format: record.format ?? null,
        width: record.width ?? null,
        height: record.height ?? null,
        ...(record.duration != null ? { duration: record.duration } : {}),
        bytes: record.bytes ?? asset.bytes,
        category: asset.category,
        ...(asset.artistId ? { artistId: asset.artistId } : {}),
        ...(asset.order != null ? { order: asset.order } : {}),
        ...(asset.carouselOrder != null ? { carouselOrder: asset.carouselOrder } : {}),
        // Kept so the application can fall back to the local file for any
        // asset that has not been migrated yet.
        source: asset.relativePath,
      };
    });

  const byCategory = {};
  for (const entry of entries) {
    (byCategory[entry.category] ??= []).push(entry);
  }
  for (const list of Object.values(byCategory)) {
    list.sort((a, b) => (a.order ?? 0) - (b.order ?? 0) || a.id.localeCompare(b.id, 'en', { numeric: true }));
  }

  return {
    generatedAt: new Date().toISOString(),
    cloudName,
    note: 'Generated by npm run media:sync. Do not edit by hand.',
    counts: Object.fromEntries(Object.entries(byCategory).map(([key, list]) => [key, list.length])),
    assets: byCategory,
  };
}

function summarise(results) {
  const byCategory = new Map();
  for (const { asset, plan } of results) {
    if (!byCategory.has(asset.category)) {
      byCategory.set(asset.category, { discovered: 0, unchanged: 0, upload: 0, replace: 0, matched: 0, duplicate: 0, failed: 0 });
    }
    const row = byCategory.get(asset.category);
    row.discovered += 1;
    if (plan.action === 'unchanged') row.unchanged += 1;
    else if (plan.action === 'upload') row.upload += 1;
    else if (plan.action === 'replace') row.replace += 1;
    else if (plan.action === 'matched-elsewhere') row.matched += 1;
    else if (plan.action === 'possible-duplicate') row.duplicate += 1;
    else if (plan.action === 'failed') row.failed += 1;
  }
  return byCategory;
}

function printSummary(byCategory, { uploaded = false } = {}) {
  const labels = {
    videos: 'Videos', carousel: 'Carousel', artists: 'Artists',
    galleries: 'Galleries', branding: 'Branding',
  };
  for (const category of CATEGORY_ORDER) {
    const row = byCategory.get(category);
    if (!row) continue;
    console.log(`\n${labels[category] ?? category}:`);
    console.log(`  ${pad(row.discovered, 4)} discovered`);
    console.log(`  ${pad(row.unchanged, 4)} unchanged`);
    if (row.matched) console.log(`  ${pad(row.matched, 4)} already in Cloudinary under another path (left alone)`);
    if (row.duplicate) console.log(`  ${pad(row.duplicate, 4)} possible duplicate of an existing asset (left alone)`);
    console.log(`  ${pad(row.upload, 4)} ${uploaded ? 'uploaded' : 'to upload'}`);
    if (row.replace) console.log(`  ${pad(row.replace, 4)} changed locally, ${uploaded ? 'replaced' : 'to replace'}`);
    if (row.failed) console.log(`  ${pad(row.failed, 4)} failed`);
  }
}

async function main() {
  loadEnvironment();
  const status = credentialStatus();

  console.log('BANG PRIVATE TATTOOS — media sync');
  console.log(`  mode          ${MODE}${DRY_RUN ? ' (dry run)' : ''}`);
  console.log(`  cloud name    ${status.cloudName || '(not configured)'}`);
  // Presence only. Values are never read into the output.
  console.log(`  credentials   api key ${status.hasApiKey ? 'present' : 'missing'}, api secret ${status.hasApiSecret ? 'present' : 'missing'}`);

  const { assets: allAssets, unsupported, missingFolders, folderMap, duplicates: repeatFiles } = await discoverMedia();
  const assets = CATEGORY_FILTER ? allAssets.filter(asset => asset.category === CATEGORY_FILTER) : allAssets;

  console.log('\nFolder mapping');
  for (const entry of folderMap) {
    console.log(`  ${entry.from.padEnd(28)} -> ${entry.to}${entry.count != null ? `  (${entry.count} files)` : ''}`);
  }
  if (missingFolders.length) {
    console.log('\nNot found on disk (skipped):');
    for (const folder of missingFolders) console.log(`  ${folder}`);
  }

  const noteworthy = assets.filter(asset => asset.noteworthy);
  if (noteworthy.length) {
    console.log(`\nUnusual but uploadable formats: ${noteworthy.length}`);
    const extensions = [...new Set(noteworthy.map(asset => asset.extension))];
    console.log(`  ${extensions.join(', ')} — JPEG data under a legacy extension; Cloudinary detects the real type.`);
  }
  const skippedDuplicates = CATEGORY_FILTER
    ? repeatFiles.filter(item => item.category === CATEGORY_FILTER)
    : repeatFiles;
  if (skippedDuplicates.length) {
    console.log(`\nRepeat of an artwork already in the sequence — skipped, left on disk: ${skippedDuplicates.length}`);
    for (const item of skippedDuplicates) console.log(`  ${item.relativePath}`);
  }
  if (unsupported.length) {
    console.log(`\nUnsupported, NOT uploaded: ${unsupported.length}`);
    for (const asset of unsupported.slice(0, 20)) console.log(`  ${asset.relativePath}`);
  }

  const state = await readJson(SYNC_STATE_PATH, {});

  // ── check: local only, no network ───────────────────────────────────────
  if (MODE === 'check') {
    const rows = new Map();
    let newCount = 0;
    let changedCount = 0;
    for (const asset of assets) {
      if (!rows.has(asset.category)) rows.set(asset.category, { discovered: 0, unchanged: 0, upload: 0, replace: 0, matched: 0, duplicate: 0, failed: 0 });
      const row = rows.get(asset.category);
      row.discovered += 1;
      const known = state[asset.relativePath];
      if (!known) { row.upload += 1; newCount += 1; }
      else if (known.sha256 !== asset.sha256) { row.replace += 1; changedCount += 1; }
      else row.unchanged += 1;
    }
    printSummary(rows);

    const orphans = Object.keys(state).filter(key => !allAssets.some(asset => asset.relativePath === key));
    if (orphans.length) {
      console.log(`\nMapped locally but no longer on disk: ${orphans.length}`);
      for (const orphan of orphans.slice(0, 20)) console.log(`  ${orphan}  ->  ${state[orphan].publicId}`);
      console.log('  These Cloudinary assets are left untouched. Removing them is a separate, explicit action.');
    }

    console.log(`\nmedia:check complete — ${newCount} new, ${changedCount} changed, ${assets.length} discovered.`);
    if (!isConfigured()) {
      console.log('Cloudinary credentials are not set, so nothing was compared against the account.');
      console.log('Add CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET to .env.local to compare and upload.');
    }
    return;
  }

  // ── sync / dry run: needs the account ───────────────────────────────────
  if (!isConfigured()) {
    console.error('\nCannot continue: Cloudinary credentials are missing.');
    console.error('Set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET in .env.local.');
    console.error('Never prefix them with VITE_ — that would publish them in the browser bundle.');
    process.exitCode = 1;
    return;
  }

  console.log('\nReading the Cloudinary account…');
  const remote = await fetchRemoteAssets();
  console.log(`  ${remote.total} assets already in the account`);

  const results = [];
  for (const asset of assets) {
    results.push({ asset, plan: planFor(asset, remote, state) });
  }

  const matched = results.filter(item => item.plan.action === 'matched-elsewhere');
  if (matched.length) {
    console.log(`\nAlready in Cloudinary under a different path — will NOT be re-uploaded: ${matched.length}`);
    for (const item of matched.slice(0, 20)) {
      console.log(`  ${item.asset.relativePath}`);
      console.log(`      remote: ${item.plan.remote.publicId}`);
    }
  }
  const duplicates = results.filter(item => item.plan.action === 'possible-duplicate');
  if (duplicates.length) {
    console.log(`\nSame size as an existing asset — left alone, review manually: ${duplicates.length}`);
    for (const item of duplicates.slice(0, 20)) {
      console.log(`  ${item.asset.relativePath}  ~  ${item.plan.remote.publicId}`);
    }
  }

  if (DRY_RUN) {
    const pending = results.filter(item => item.plan.action === 'upload' || item.plan.action === 'replace');
    console.log(`\nWould upload ${pending.length} asset${pending.length === 1 ? '' : 's'}:`);
    for (const item of pending.slice(0, 40)) {
      console.log(`  ${item.plan.action === 'replace' ? 'replace' : 'upload '}  ${item.asset.relativePath}`);
      console.log(`           -> ${item.asset.publicId}  [${item.asset.resourceType}]`
        + (item.asset.assetFolder ? `  asset_folder=${item.asset.assetFolder}` : ''));
    }
    if (pending.length > 40) console.log(`  … and ${pending.length - 40} more`);
    printSummary(summarise(results));
    console.log('\nDry run — nothing was uploaded and nothing in Cloudinary was changed.');
    return;
  }

  // ── real upload ─────────────────────────────────────────────────────────
  const nextState = { ...state };
  /** Reported again at the end, so a failure in a long run is not scrolled away. */
  const failures = [];
  for (const item of results) {
    const { asset, plan } = item;

    if (plan.action === 'unchanged') continue;

    if (plan.action === 'matched-elsewhere' || plan.action === 'possible-duplicate') {
      // Record the mapping so the existing remote asset is used rather than a
      // second copy being created on a later run.
      nextState[asset.relativePath] = {
        publicId: plan.remote.publicId,
        resourceType: plan.remote.resourceType,
        format: plan.remote.format,
        bytes: plan.remote.bytes,
        width: plan.remote.width,
        height: plan.remote.height,
        duration: plan.remote.duration,
        version: plan.remote.version,
        sha256: asset.sha256,
        adopted: true,
      };
      continue;
    }

    try {
      process.stdout.write(`  ${plan.action === 'replace' ? 'replace' : 'upload '} ${asset.relativePath} … `);
      const uploaded = await uploadAsset(asset);
      nextState[asset.relativePath] = { ...uploaded, sha256: asset.sha256 };
      console.log('done');
    } catch (error) {
      item.plan = { action: 'failed', remote: null };
      failures.push({ relativePath: asset.relativePath, reason: describeUploadError(error) });
      // Message only. The full error object is never printed.
      console.log(`FAILED (${describeUploadError(error)})`);
    }
  }

  await writeJson(SYNC_STATE_PATH, nextState);
  const manifest = buildFrontendManifest({ assets: allAssets, state: nextState, cloudName: status.cloudName });
  await writeJson(FRONTEND_MANIFEST_PATH, manifest);

  printSummary(summarise(results), { uploaded: true });

  if (failures.length) {
    console.log(`\n${failures.length} upload${failures.length === 1 ? '' : 's'} failed and ${failures.length === 1 ? 'was' : 'were'} NOT recorded:`);
    for (const failure of failures) console.log(`  ${failure.relativePath}\n      ${failure.reason}`);
    console.log('  Nothing was deleted. Re-running the sync retries exactly these.');
    process.exitCode = 1;
  }

  console.log(`\nSync state  ${path.relative(PROJECT_ROOT, SYNC_STATE_PATH)}`);
  console.log(`Manifest    ${path.relative(PROJECT_ROOT, FRONTEND_MANIFEST_PATH)}`);
  console.log('\nMedia sync complete. No Cloudinary asset was deleted.');
}

main().catch(error => {
  console.error(`\nmedia sync failed: ${error instanceof Error ? error.message : 'unknown error'}`);
  process.exitCode = 1;
});
